Local node setup
onPoster/contract pull request #25
Opened 2021-12-24 11:14 UTC by jjperezaguinaga

See onPoster/app#80 for more information.

- Provided the basic commands for running and deploy the contracts locally. Follow-up work will be done in onPoster/subgraph#6.

2021-12-29 07:02 UTC, auryn-macmillan requested changes
Changes to the deploy script look good.
I don't think we should default to localhost.

2021-12-29 07:02 UTC, auryn-macmillan commented on package.json
>      "@graphprotocol/graph-cli": "^0.18.0",
hhhmm, why is the graph added as a dependency to this repo?

2021-12-30 14:12 UTC, jjperezaguinaga commented on hardhat.config.ts
> +const defaultNetwork = "localhost";
Ah, good call, let me update it. Also probably good I add a CI test to avoid these things to happen.

2021-12-30 14:12 UTC, jjperezaguinaga commented on package.json
>      "@graphprotocol/graph-cli": "^0.18.0",
Actually good catch, no idea, let me remove it.

2021-12-31 11:56 UTC, jjperezaguinaga commented on hardhat.config.ts
> +const defaultNetwork = "localhost";
Solved in 9140ef4802cda381f2df1c2c06e00ad7af19c5bb, added CI in e5dd99a0fec4670ba564e0621bae1711d1efd751

2021-12-31 11:56 UTC, jjperezaguinaga commented on hardhat.config.ts
> +  defaultNetwork,
Completed in 9140ef4802cda381f2df1c2c06e00ad7af19c5bb

2021-12-31 11:57 UTC, jjperezaguinaga commented on package.json
>      "@graphprotocol/graph-cli": "^0.18.0",
Removed in 9140ef4802cda381f2df1c2c06e00ad7af19c5bb

2022-01-01 00:28 UTC, auryn-macmillan approved these changes
Lgtm!

2022-01-03 02:18 UTC, merged